name: Deploy

on:
  push:
    branches:
      - master
      - develop

env:
  # DEV environment settings.
  GCP_BUCKET_DEV: 'gs://tabak-house-development'
  GCP_BUCKET_DEV_CACHE: 'public, max-age=60'

  # PRODUCTION environment settings.
  GCP_BUCKET_PROD: 'gs://tabak-house-production'
  GCP_BUCKET_PROD_CACHE: 'public, max-age=3600'

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: NPM cache
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('./package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('./package-lock.json') }}

      - name: Install NPM dependencies
        run: npm ci

      - name: Run linters
        run: npm run lint

      - name: Build
        run: npm run build

      - name: 'Deploy: Development'
        if: ${{ github.ref == 'develop' }}
        run: 'gsutil -m -h "Cache-Control: ${{ env.GCP_BUCKET_DEV_CACHE }}" rsync -d -r ./dist ${{ env.GCP_BUCKET_DEV }}'

      - name: 'Deploy: Production'
        if: ${{ github.ref == 'master' }}
        run: 'gsutil -m -h "Cache-Control: ${{ env.GCP_BUCKET_PROD_CACHE }}" rsync -d -r ./dist ${{ env.GCP_BUCKET_PROD }}'
